### ISSUE TITLE
生成clash配置后导入clash报错

### ISSUE THREAD

**Issue by xiaolilir** [surgioproject/surgio#121]
‘’‘
level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"
’‘’

**Comment by xiaolilir** [comment]
这个是用其他的工具生成的proxies 👍 proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - qqlight
      - sav3
      - xianyu2
      - virmach
      - silk
      - oraclegmail
      - unit
      - hostyun
      - raksmart
      - vultr
下面使用surgio生成的:
proxy-groups:
- type: select
  name: 🚀 Proxy
  proxies: ["sharktech","qqlight","sav3","xianyu2","virmach","silk","oraclegmail","unit","hostyun","raksmart","vultr"]
- type: select
  name: 🎬 Netflix
  proxies: []
- type: url-test
  name: US
  proxies: []
  url: http://cp.cloudflare.com/generate_204
  interval: 1200
- type: url-test
  name: HK
  proxies: []
  url: http://cp.cloudflare.com/generate_204
  interval: 1200
- type: select
  name: 🍎 Apple
  proxies:
    - DIRECT
    - 🚀 Proxy
    - US
    - HK
- type: select
  name: 🍎 Apple CDN
  proxies:
    - DIRECT
    - 🍎 Apple

**Comment by geekdada** [comment]
确认是没问题的，请检查你的 Clash 版本

**Comment by caiking** [comment]
我遇到了同样的问题

**Comment by geekdada** [comment]
确认自己的 Clash 模板已经更新

**Comment by juzi214032** [comment]
我也遇到这个问题了

**Comment by lockie185** [comment]
看看是否缺少节点，我也出现同样的问题，在前面缺少： proxy-groups:

**Comment by zealxz** [comment]
建议更换其他软件如Hiddify后用同样链接导入问题得到解决，顺便记得上传的时候码住自己的url
