### ISSUE TITLE
文档中有些内容与实际版本不匹配

### ISSUE THREAD

**Issue by Mosaic67** [surgioproject/surgio#127]
比如 [快速搭建托管 API](https://surgio.js.org/guide/advance/api-gateway.html#%E5%BF%AB%E9%80%9F%E6%90%AD%E5%BB%BA%E6%89%98%E7%AE%A1-api)，按照流程无法顺利搭建。部署实际情况与文档不符。希望可以更新下文档。

**Comment by geekdada** [comment]
具体哪里存在不符麻烦指出一下。因为 Vercel 也在不断迭代，我很难保证一致。

**Comment by Mosaic67** [comment]
![image](https://user-images.githubusercontent.com/10384260/97092873-0b84b600-167a-11eb-8cbc-a5be90a46efb.png)

这是Build `Log`
> 04:18:36.664  	Retrieving list of deployment files...
> 04:18:38.242  	Downloading 26 deployment files...
> 04:18:39.096  	Analyzing source code...
> 04:18:39.432  	Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in > > your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings



按照步骤到了部署，前面文件都建了，surgio是新克隆下了的，路由也下载了，用`vercel --prod`命令部署，发布上去后部署报错

**Comment by geekdada** [comment]
这只是个warning,没有关系的

**Comment by Mosaic67** [comment]
但是不往下部署了，地址访问也是404

**Comment by geekdada** [comment]
你的 vercel.json 配置不正确
