### ISSUE TITLE
配置文件自带变量有proxyTestInterval，而模板变量里面没有这个，导致定义了也无法引用

### ISSUE THREAD

**Issue by StarStar-Lab** [surgioproject/surgio#131]
在文档中配置文件变量部分提到了proxyTestInterval这个变量，然而在模板变量部分没有写，在实际使用过程中也发现模板中无法引用此变量。

**Comment by geekdada** [comment]
这个配置有点过时了，原本是给 Clash 用的。因为间隔对于不同节点不同情况下可能会有不同的取值，这个没有绝对正确的，所以没有暴露在模板里。
