### ISSUE TITLE
joi包的引入方式，已经变更，可能导致Vercel托管抛502, Code: NO_RESPONSE_FROM_FUNCTION

### ISSUE THREAD

**Issue by itskaiway** [surgioproject/surgio#132]
控制台输出以下信息，不知道是不是joi的校验，导致服务端直接抛出上述错误。

21:04:43.518 | warning surgio > @hapi/joi@17.1.1: Switch to 'npm install joi'
-- | --
21:04:43.824 | warning surgio > @hapi/joi > @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
21:04:43.828 | warning surgio > @hapi/joi > @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
21:04:43.831 | warning surgio > @hapi/joi > @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'

**Comment by gqbre** [comment]
同样的问题，刚出现没几天的样子

**Comment by geekdada** [comment]
warning 可以忽略，502 是别的原因引起的。

**Comment by gqbre** [comment]
@itskaiway 解决了吗？我用官方文档里的方式重新发布，还是 502。项目可以访问，配置文件地址 502

**Comment by geekdada** [comment]
本地可以生成规则吗？

**Comment by geekdada** [comment]
@gqbre @itskaiway 

1. 首先检查本地能不能正常生成
2. 检查是不是因为花花的规则没更新地址导致的

**Comment by gqbre** [comment]
@geekdada  还真的是因为规则 404 了.. 感谢

**Comment by itskaiway** [comment]
> @itskaiway 解决了吗？我用官方文档里的方式重新发布，还是 502。项目可以访问，配置文件地址 502
> @geekdada 演示资源也是 502 ：https://demo-beta.now.sh/get-artifact/Clash.yaml?access_token=YOUR_PASSWORD

已解决，你可以先本地generate一下，把报错的一些404资源替换一下

**Comment by itskaiway** [comment]
> @geekdada 还真的是因为规则 404 了.. 感谢
> ~npm init surgio-store 初始化的仓库规则配置还是旧版~ npm taobao 源上还是旧版，已点手动同步

以后托管有问题，建议还是先本地跑一下~没问题的话，托管肯定也不会有问题，前面这个错误，我后面猜测也估计是一些规则的问题导致的，所以本地把一些404的资源重新处理了下。
