### ISSUE TITLE
vercel报错shared_utils_1.addLeadingSlash is not a function

### ISSUE THREAD

**Issue by zt900403** [surgioproject/surgio#134]
最新版本，2.7.4  gateway是1.2.1
vercel会报错
![image](https://user-images.githubusercontent.com/7888336/101898639-6ef58380-3be7-11eb-947f-a901d525622f.png)
这是next.js版本的问题？

**Comment by geekdada** [comment]
我没法重现这个问题，如果可以的话加我到你的仓库我帮你看看。

**Comment by zt900403** [comment]
之前是照着教程，在gitlab部署的， gateway降低到1.2.0问题木有了。谢谢作者。
