### ISSUE TITLE
getNodeNames 时过滤后节点列表为空导致配置错误

### ISSUE THREAD

**Issue by YOUSIKI** [surgioproject/surgio#136]
我遇到的场景是这样的，编写 Surge 规则时有一个这样的 Proxy Group：

```
🎮 游戏节点 = select,{{ getNodeNames(nodeList, customFilters.gameFilter) }}
```

但是机场更新后 gameFilter 过滤出来游戏节点为空，导致生成的配置文件是

```
[Proxy Group]
...
🎮 游戏节点 = select,
...
```

我想也许可以在过滤时设置过滤结果为空时的特别处理方式，比如如果过滤结果为空，则返回一个设置的 fallback 节点，酱紫？或者是我可不可以如下这样编写 Template：

```
🎮 游戏节点 = select,{{ getNodeNames(nodeList, customFilters.gameFilter) }},🚀 节点选择
```

像这样保证至少有一个 Proxy。但是这样又会因为输出的配置包含连续的 `,,` 而出错。

```
🎮 游戏节点 = select,,🚀 节点选择
```

不知道对于类似情况有没有优雅的解决方案，请教教我这个小白。

**Comment by geekdada** [comment]
```
{{ getNodeNames(nodeList, customFilters.gameFilter) || '🚀 节点选择' }}
```

**Comment by YOUSIKI** [comment]
哇哦，感谢 Thanks♪(･ω･)ﾉ
