### ISSUE TITLE
[FRs][BUG] artifacts sharing in respective guest access token for safety concern

### ISSUE THREAD

**Issue by jukrb0x** [surgioproject/surgio#137]
![image](https://user-images.githubusercontent.com/15688641/107257725-f3dd0c00-6a75-11eb-9334-11675aa22fb2.png)

Noted that a single artifact can be shared via link, other artifacts won't be seen in this way. Actually, the access token can be obtained in the URL.
```
https://link-to-surgio/embed/artifact/example.conf?access_token=securityLEAK
```
Anyone is able to log in to the system with this access token. I consider this is a serious security breach. 

The solution, properly. goes with a second access token so called Guest token and it can be generated or destroyed as admin wants. I would like a random generation instead of a user-defined one for a higher security requirement, and different artifacts do not share the same access token, the respective access token generated as soon as they are shareable.

**Comment by geekdada** [comment]
Thank you for your issue.

This is a known flaw. I considered this feature as a convenient way to share your config with your friends and family members, so security is not in its priority.
