### ISSUE TITLE
[BUG] 生成 http 节点 for surge 时会多一个逗号

### ISSUE THREAD

**Issue by yodakanohoshi98** [surgioproject/surgio#138]
![image](https://user-images.githubusercontent.com/78969907/108171746-f22adc80-7136-11eb-80e8-42a52fd7ee40.png)
经过测试，只会出现在未设定 username 的情况下

**Comment by geekdada** [comment]
这个会影响使用么？

**Comment by yodakanohoshi98** [comment]
> 这个会影响使用么？

不影响使用，只是强迫症难顶

**Comment by geekdada** [comment]
配置文件给程序看的，就不修复这个了
