### ISSUE TITLE
SurgeV3_ssr->Invalid line #138: 🎬 Netflix = select

### ISSUE THREAD

**Issue by Vanson** [surgioproject/surgio#141]
surgio: 2.7.7 
node: 12.16.2 (/usr/local/bin/node)
npx: 6.14.4
npm: 6.14.4
shadowsocks-libev 3.3.5 install by homebrew

npx surgio generate success ,SurgeV3_ssr.conf show error in  Surge版本4.0.4 (1227)

**Comment by geekdada** [comment]
检查节点名是不是没有符合要求的，所以列表为空
