### ISSUE TITLE
部署至 Vercel 会报 500 INTERNAL_SERVER_ERROR 错误信息：`Code: FUNCTION_INVOCATION_FAILED`

### ISSUE THREAD

**Issue by muxinqi** [surgioproject/surgio#142]
## 错误提示
![Vercel-500](https://i.loli.net/2021/03/09/dOxLyiRtMGjnIlA.png)

<br />

## 问题描述
在修改并部署已有项目后，会出现如上图所示错误。
创建一个新项目之后，问题依旧。

**目前情况：**
- 本地可正常 `npx surgio generate` 生成规则文件。
- 本地使用 `vercel dev` 可正常访问 `localhost:3000` surgio auth 界面

<br />

## 复现步骤

```bash
$ npm init surgio-store surgio-demo
$ cd surgio-demo
$ npm i
```

接着按照 [快速搭建托管 API - 搭建 Vercel](https://surgio.js.org/guide/advance/api-gateway.html#%E5%89%8D%E8%A8%80) 所述， 完成 `@surgio/gateway` 和 Vercel 相关配置。

上传 GitHub，添加至 Vercel 并自动部署。

<br />

## 已实施措施

个人认为不排除 Vercel 那边的问题，所以给他们提了个工单，在等待回复中。

<br />

## 问题复现 Demo

Vercel: https://surgio-demo-kappa.vercel.app/
仓库：https://github.com/muxinqi/surgio-demo

<br />

## 环境信息

```bash
$ node -v
v14.16.0

$ npm -v
6.14.11

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
```

**Comment by ab00b** [comment]
我这边也出现了同样的问题，一样的错误提示
当我按照一个[旧一些的教程](https://www.notion.so/Surgio-373256ca4ac547479a09cc561be576fd)没有用vercel.json而是用的now.json，内容如下，可以正常工作
'''
{
  "version": 2,
  "public": false,
  "builds": [
    {
      "src": "/gateway.js",
      "use": "@now/node",
      "config": {
        "includeFiles": ["provider/**", "template/**", "*.js", "*.json"]
      }
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "/gateway.js"
    }
  ]
}
'''
可以试试这样旧的方法

**Comment by geekdada** [comment]
Vercel 的一个组件昨天升级了，会导致面板重新部署后无法使用，目前临时的解决方法就是修改 vercel.json 中的 `"use": "@vercel/node@1.9.0"`（如图），我会检查是我的代码不规范还是 Vercel 的问题导致的。

![IMAGE 2021-03-10 13:21:52](https://user-images.githubusercontent.com/3274850/110580404-9686c880-81a3-11eb-84cb-a45c8758fda4.jpg)

**Comment by muxinqi** [comment]
@ab00b 
@geekdada 

十分感谢，试了上面的两种方法，都是可行的！

**Comment by rookiezq** [comment]
你好我想问一下，部署在vercel后可以自动更新机场订阅吗？

**Comment by geekdada** [comment]
@rookiezq 可以，不过 Surgio 有段缓存的时间

**Comment by rookiezq** [comment]
那他是怎么自动更新的呢？我好像没找到跟gitlab类似的定时机制

**Comment by geekdada** [comment]
@rookiezq surgio 会保留十分钟上一次请求到的订阅。你可以在面板中点击「清除缓存」来清除订阅。
