### ISSUE TITLE
托管和自动更新的一些问题

### ISSUE THREAD

**Issue by rookiezq** [surgioproject/surgio#147]
想问一下，vercel支持自动更新吗，我看了文档好像没找到，只看到需要手动vercel --prod才行，不知道是不是遗漏了什么？
应该如何做到自动更新规则并且自动订阅呢？

**Comment by rookiezq** [comment]
补充一下：gitlab如果是私有的话，应该就不支持urlBase改成gitlab了吧？

**Comment by geekdada** [comment]
- Vercel 里绑定 GitHub 和 GitLab 应用就可以自动更新。
- 这个属性和私有库没关系，公网不直接从 GitLab 读取。
