### ISSUE TITLE
规则支持的关键词建议更新一下版本

### ISSUE THREAD

**Issue by fbigun** [surgioproject/surgio#148]
[clash rules](https://lancellc.gitbook.io/clash/clash-config-file/rules/ip-based-rule)

clash 已经支持 `IP-CIDR&IP-CIDR6` 支持 `Option: no-resolve`关键词。  `GEOIP`也能支持 `Option: no-resolve`。

clash 现在支持的关键词均有很大的变化了。建议更新啊

**Comment by fbigun** [comment]
增加 surfboard 的 Artifact

**Comment by geekdada** [comment]
感谢反馈，会更新 Clash 的相关功能。Surfboard 可以直接使用 Surge 2 的配置。
