### ISSUE TITLE
clash 规则已经支持 PROCESS-NAME

### ISSUE THREAD

**Issue by fbigun** [surgioproject/surgio#150]
文档
https://lancellc.gitbook.io/clash/clash-config-file/rules/process-based-rule

不知道有没有支持的想法

**Comment by geekdada** [comment]
会在近期支持

**Comment by geekdada** [comment]
搞忘了这个 ticket…

**Comment by fbigun** [comment]
已经支持了啊。

**Comment by geekdada** [comment]
😂 

Close it
