### ISSUE TITLE
订阅节点通过renameNode方法重命名节点重名出错

### ISSUE THREAD

**Issue by fbigun** [surgioproject/surgio#151]
在节点通过renameNode方法应用后能提供勾子修饰重名节点，或者自主增加流水号保证节点名唯一

**Comment by geekdada** [comment]
出错，什么错？

**Comment by fbigun** [comment]
意思就是订阅的时候有两个名为如下的两个节点
```
香港节点ok101
香港节点101
```
修改者不经意通过renameNode方法移除第一个`ok`字段后，这个节点里面的不经意的就出现两个节点同名，然后就出现重名出错了，结果后自动丢弃一个节点

**Comment by geekdada** [comment]
这个通常非常容易规避吧，而且也不容易遇到

**Comment by fbigun** [comment]
如果订阅的节点中有名称重复的符合处理，如v2ray的订阅就有许多的节点名称都是重复的。
