### ISSUE TITLE
usFilter 过滤问题

### ISSUE THREAD

**Issue by harryyifei** [surgioproject/surgio#155]
请问 usFilter 为什么会过滤出俄罗斯和澳大利亚节点，麻烦大大帮忙看看
![CleanShot 2021-08-29 at 14 31 22](https://user-images.githubusercontent.com/49369802/131241036-b72415d9-5a69-4c20-8230-96f2f9b33107.jpg)

**Comment by geekdada** [comment]
因为有 us 这两个字母...

**Comment by harryyifei** [comment]
请问大大如何加一个过滤出的filter呢…语法搞不明白😂
