### ISSUE TITLE
surfboard使用vmess节点时 wsheader格式有误

### ISSUE THREAD

**Issue by avalanceonerd** [surgioproject/surgio#156]
https://github.com/surgioproject/surgio/blob/d10561243ee0db76e0ca5e6281ae44d49c8c528f/lib/utils/index.ts#L372-L385

这里wsheader最终会输出 ws-headers="host:xxxx"  如果手动改成 ws-headers=host:xxxx 在surfboard里面用就没问题了 是否有历史原因导致这里要JSON字符串化呢?

**Comment by geekdada** [comment]
因为 `user-agent` 里有特殊字符（比如空格）。

**Comment by avalanceonerd** [comment]
> 因为 `user-agent` 里有特殊字符（比如空格）。

那是不会改成wa-header=key:value;形式了吗
user-agent可否置位可选内容 这个应该不是必须的吧

**Comment by geekdada** [comment]
这个格式在 Surge 上是可以正常使用的
