### ISSUE TITLE
请求订阅地址超时

### ISSUE THREAD

**Issue by richieliuse** [surgioproject/surgio#160]
无论是否开启provider.relayurl，请求订阅地址都会超时。error log显示“Timeout awaiting 'request' for 5000ms”。如何手动设置请求超时时间。

**Comment by fbigun** [comment]
可以设定环境变量 
export SURGIO_NETWORK_TIMEOUT=20s

**Comment by geekdada** [comment]
https://surgio.js.org/guide/env.html#surgio-network-timeout

注意单位是**秒**

**Comment by kpictor** [comment]
请问怎么添加环境变量？是在conf.js 中什么位置添加什么，谢谢！
