### ISSUE TITLE
请问文档这里是不是没写完

### ISSUE THREAD

**Issue by lincww** [surgioproject/surgio#164]
![image](https://user-images.githubusercontent.com/56734434/145710277-9ffd4f28-de02-4a3d-9bb7-14ed60fe4bc6.png)
是[here](https://github.com/surgioproject/surgio/blob/master/docs/guide/custom-provider.md)的第426行
多谢！

**Comment by geekdada** [comment]
感觉是意外删掉了……多谢指出！
