### ISSUE TITLE
更多的部署平台选择？

### ISSUE THREAD

**Issue by aozaki-kuro** [surgioproject/surgio#165]
最近刚刚成功折腾好部署，非常感谢作者写了这么一个project。
关于目前可选的部署平台有一些疑问

1. 我看到issue里提及部署在Vercel会封号，目前是否解决了呢？
2. 由于Heroku的免费tier不能套Cloudflare，裸连在大陆的连通性相当差所以几乎没法正常使用；Railway的裸连似乎也不怎么好，但是可以套CF但是部署速度会比较慢（修改后重新部署及等待刷新时间较长）。所以想询问是否有其他的平台可选部署？
3. 如果是host在自己的VPS上，是否还可以及时刷新订阅缓存？还是需要手动执行？

谢谢！

**Comment by geekdada** [comment]
你可以参照[这个教程](https://surgio.js.org/guide/advance/api-gateway.html#%E9%83%A8%E7%BD%B2-%E8%87%AA%E6%9C%89%E6%9C%8D%E5%8A%A1%E5%99%A8)自己部署，可以自动刷新订阅缓存，功能和部署在 Vercel 上是一样的。

**Comment by aozaki-kuro** [comment]
已经选择部署到自己的服务器上，通过pm2启动/管理
有修改时重构建时间大大缩短，功能也正常
