### ISSUE TITLE
请求新增Trojan订阅处理以及修复udp转发

### ISSUE THREAD

**Issue by aozaki-kuro** [surgioproject/surgio#166]
您好，近期发现各家机场在逐渐换用Trojan协议，而Surgio无法处理Trojan通用订阅，希望增加对Trojan通用订阅的支持。

另外发现：
Provider为 \*含Trojan节点的Clash配置文件\* ，添加了`udpRelay: true`且原配置文件含有`udp: true`属性。
生成Surge配置文件时发现原来含有的udp转发支持丢失，同时Clash订阅可以正常添加udp转发。
希望可以修复这个问题。

目前使用版本
```json
"dependencies": {
    "@surgio/gateway": "^1.4.1",
    "surgio": "^2.10.3"
  },
```
谢谢！

**Comment by fgprodigal** [comment]
也有机场提供trojan的surge node list，能否provider支持一下surge的node list

**Comment by geekdada** [comment]
@fgprodigal 你好，新增一种订阅的支持是非常麻烦的，不仅要考虑 Trojan 还要考虑其它所有 Surgio 已经支持的协议，所以不再考虑新增。

**Comment by geekdada** [comment]
@aozaki-kuro 你好。

关于第一个问题，我没有找到 Trojan 官方定义的订阅格式或者 URL Scheme 格式，不知道有没有。假如没有的话我还是宁愿支持 Clash 订阅，因为 Clash 订阅包含了完整的节点信息。
关于第二个问题，Surge 目前只支持 Shadowsocks 的 UDP 协议。

**Comment by geekdada** [comment]
URL Scheme 的解析可以参照这个 https://github.com/trojan-gfw/trojan-url ，不过没说节点名称怎么处理

**Comment by fgprodigal** [comment]
> @fgprodigal 你好，新增一种订阅的支持是非常麻烦的，不仅要考虑 Trojan 还要考虑其它所有 Surgio 已经支持的协议，所以不再考虑新增。另外，不可能有机场仅提供 Surge 订阅不提供 Clash 订阅。

他提供了ssr的clash订阅和trojan的surge node list😂，现在我自己转了一下用了

**Comment by geekdada** [comment]
已在 [v2.11.0](https://github.com/surgioproject/surgio/releases/tag/v2.11.0) 中增加读取 Shadowsocks 节点。
