### ISSUE TITLE
surgio 没有完全支持 V2rayN 订阅地址

### ISSUE THREAD

**Issue by fbigun** [surgioproject/surgio#167]
[V2rayN 订阅功能说明](https://github.com/2dust/v2rayN/wiki/%E8%AE%A2%E9%98%85%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E)

订阅说明中支持vmess/ss/socks，但同样的订阅地址，surgio会吞掉除 vmess 外的其他节点

**Comment by geekdada** [comment]
V2rayN 应该是后来增加的其它协议支持，Surgio 还没跟上

**Comment by fbigun** [comment]
速度👍
