### ISSUE TITLE
getClashNodeNames是否不支持这样的写法

### ISSUE THREAD

**Issue by jwstaceyOvO** [surgioproject/surgio#168]
- type: select
  name: 🎬Netflix
  proxies: {{ getClashNodeNames(nodeList, ['🔰国外流量']) | json }}

  Error: 使用了无效的过滤器 🔰国外流量

   如果前面加入Filter参数则运行正常

**Comment by geekdada** [comment]
文档： https://surgio.js.org/guide/custom-template.html#getclashnodenames

你也不能想当然就写上去然后没效果就说它不正常啊……
