### ISSUE TITLE
希望增加网页上直接修改provider的nodeList

### ISSUE THREAD

**Issue by Neo-peng** [surgioproject/surgio#176]
目前使用surgio管理自己的几个节点，但是每次有新增节点都需要去服务器手动修改provider的nodeList，请问是否可以增加对custom类型provider在网页上可视化的增删改节点功能？

**Comment by Neo-peng** [comment]
> 不过

我确实用的自己的服务器部署的，所以如果要自动部署的需要用到什么工具？

**Comment by geekdada** [comment]
试试搜索“Github Action SSH 部署”
