### ISSUE TITLE
有计划支持wireguard么？

### ISSUE THREAD

**Issue by DockerCS** [surgioproject/surgio#184]
Surge商店版本已经支持wireguard了

**Comment by geekdada** [comment]
是否可以直接将节点写在模板中？

**Comment by miniers** [comment]
> 是否可以直接将节点写在模板中？

这个，虽然完全可以，但是，有些不太优雅😂

**Comment by geekdada** [comment]
我先研究一下怎么支持可以比直接写在模板中更简单。

**Comment by linwanxiaoyehua** [comment]
> 我先研究一下怎么支持可以比直接写在模板中更简单。

wing文现在支持了吗

**Comment by linwanxiaoyehua** [comment]
> 我先研究一下怎么支持可以比直接写在模板中更简单。

请问现在支持了吗

**Comment by tediorelee** [comment]
stash现在能将wireguard作为layer 4的代理使用了，希望provider的类型可以增加支持wireguard

**Comment by geekdada** [comment]
已在之前版本中支持，关闭这个 issue
