### ISSUE TITLE
允许给 got 添加 rejectUnauthorized 配置

### ISSUE THREAD

**Issue by zieglar** [surgioproject/surgio#185]
有个机场的证书有问题，更新时产生 Unable to verify the first certificate 错误，希望 surgio 的 httpclient 能添加一个配置来控制 https 的 rejectUnauthorized

**Comment by geekdada** [comment]
最好是联系机场解决而不是通过别的方法绕过。

机场的订阅可以直接通过浏览器访问吗？

**Comment by zieglar** [comment]
已经上报给机场，可以通过浏览器访问，但是浏览器有补偿机制 ，希望 surgio 能处理是最好 https://zhuanlan.zhihu.com/p/108958388

**Comment by geekdada** [comment]
请尝试这个办法，Surgio 将不会在内部处理这种情况 https://www.npmjs.com/package/ssl-root-cas#important-try-this-next
