### ISSUE TITLE
underlyingProxy参数可否在provider中使用？

### ISSUE THREAD

**Issue by hououinkami** [surgioproject/surgio#187]
目前underlyingProxy参数只能使用于nodeConfig中，因为某些场合有批量添加的需求，我试着将其写在provide里，但并不生效。
请问是我的操作有问题还是说本来就不支持呢？
若不支持的话是否可以让underlyingProxy参数也可以在provider中生效呢？
谢谢！

**Comment by geekdada** [comment]
会在后续版本中支持

**Comment by geekdada** [comment]
已支持 https://surgio.js.org/guide/custom-provider#provider-underlyingproxy
