### ISSUE TITLE
使用 export-providers 导出的 Clash Provider 报错

### ISSUE THREAD

**Issue by huangyafei** [surgioproject/surgio#193]
之前一直是没问题的，不清楚最近是 Clash 的语法变了还是 Surgio 升级后改了什么，现在生成的 Clash Provider 会报错：

```
Parse config error: initial proxy provider xxxxx error: Get \"https://xxx.herokuapp.com/get-artifact/Clash.yaml?format=clash-provider&filter=customFilters.mediaFilter&access_token=xdfealvPesJkrqLfg\": context deadline exceeded
```

我看导出的 Provider 文件里末尾最后一行有 `...`，跟 Clash 文档里的示例不一样，不确定是不是这个原因。

**Comment by geekdada** [comment]
请更新 @surgio/gateway@1.6.4

**Comment by huangyafei** [comment]
> 请更新 @surgio/gateway@1.6.4

大大，貌似还有个 bug，export-providers 导出的 Clash Provider 缩进有问题，所以还是会报错，我自己试了下，手动调整下缩进才能正常使用，你可以看下下面的图，左侧是 Surgio 网关导出的，右侧是我手动调整的，实际使用中只有右侧的才不会报错。

![SCR-20220601-m3a](https://user-images.githubusercontent.com/1579347/171355875-f21ebd9f-fbc1-464b-8c99-70493fd94c77.png)

**Comment by geekdada** [comment]
请更新 @surgio/gateway@1.6.5

好奇怪，这个模板其实 2 年前就是这样了。要么就是没人用，要么就是 Clash 改了什么。

**Comment by huangyafei** [comment]
> 

解决了，谢谢大大。
不过是好奇怪，之前一直用的好好的，大概就是从5月份开始的，可能是 Clash 改了什么吧。
