### ISSUE TITLE
使用指定代理（CDN）反代插件和配置文件中的 Github 地址，以防止配置文件下载失败，格式参考： https://ghproxy.com/

### ISSUE THREAD

**Issue by bytemain** [surgioproject/surgio#209]
OpenClash 有这个功能：
<img width="957" alt="CleanShot 2022-10-10 at 12 26 22@2x" src="https://user-images.githubusercontent.com/13938334/194799245-998dbe11-69aa-43f7-8721-5e6554028cda.png">

<img width="899" alt="CleanShot 2022-10-10 at 12 26 39@2x" src="https://user-images.githubusercontent.com/13938334/194799256-7886b176-c937-453e-ae79-9fc2fabc3c31.png">

对于第一次拉取配置的人很方便，用 GitHub 的 raw 老是会出现拉不下来。

**Comment by bytemain** [comment]
emmm 我的意思是希望 surgio 可以支持这个功能

**Comment by geekdada** [comment]
我觉得不是很必要，这个自己需要可以自己加
