### ISSUE TITLE
Tuic 都支持了，什么时候支持 Hysteria？

### ISSUE THREAD

**Issue by kchen0x** [surgioproject/surgio#211]
如题

**Comment by geekdada** [comment]
目前 Surgio 主要面向的几款客户端（Quantumult X, Surge, Clash）都没有支持 Hysteria

**Comment by EkkoG** [comment]
Stash 已支持 Hysteria https://stash.wiki/proxy-protocols/proxy-types#hysteria

clash-verge 因为可以使用 Clash.Meta 内核，也是支持 Hysteria 的 https://wiki.metacubex.one/config/proxies/hysteria/

**Comment by geekdada** [comment]
OK，计划支持

**Comment by kchen0x** [comment]
Surge 已经支持 Hysteria2，可以考虑安排上了。
还有ECN的支持。 加油！

**Comment by kchen0x** [comment]
看到 Author 我才意识到，这个问题就是我自己提的……

**Comment by geekdada** [comment]
新版已支持该特性
