### ISSUE TITLE
Gateway 为Artifacts指定特定 accessToken

### ISSUE THREAD

**Issue by VaalaCat** [surgioproject/surgio#215]
当与他人分享Artifacts时共用一个token会导致安全问题

**Comment by geekdada** [comment]
`viewerToken` https://surgio.js.org/guide/custom-config.html#gateway-viewertoken 是否能满足需求？

**Comment by VaalaCat** [comment]
比如有两个artifact A B，一些人用A另一些人用B，但viewertoken二者相同，没有隔离A、B的权限

**Comment by geekdada** [comment]
暂不考虑支持这个特性。Surgio 主要面向个人使用。
