### ISSUE TITLE
传递 subscription-userinfo 标头以支持用户信息显示

### ISSUE THREAD

**Issue by xkww3n** [surgioproject/surgio#222]
Clash for Windows等软件均支持通过读取 subscription-userinfo 标头来显示用户信息（已用流量，可用流量，过期日期），如 `subscription-userinfo: upload=2375927198; download=12983696043; total=1099511627776; expire=1862111613`。很多机场也已支持这一特性，希望 Surgio 在处理订阅时可以同时处理此标头。

**Comment by fbigun** [comment]
下载文件时，如果 http header  有 file 的标头也会处理下载后的文件名，希望也能同步处理
