### ISSUE TITLE
2.25.0 生成的项目，clash 数组规则，没有 -

### ISSUE THREAD

**Issue by defp** [surgioproject/surgio#224]
<img width="2095" alt="image" src="https://user-images.githubusercontent.com/612381/223091142-fb1c18fd-e375-48a1-af3f-e08896ba6af0.png">

默认生成的没有 | clash
加了 | clash 配置后，dist 目录生成的配置文件也没有 -

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/612381/223091332-096847bb-fa63-4c95-a264-6a077343c366.png">

**Comment by geekdada** [comment]
被第 55 行影响了
