### ISSUE TITLE
请问 trojan 输出 UDP 的配置问题

### ISSUE THREAD

**Issue by harryyifei** [surgioproject/surgio#227]
在 provider 中配置了 udpRelay: true, 但在输出的 trojan 节点中好像并没有成功配置，请问是 trojan 配置中的语法有不同的写法吗？

**Comment by geekdada** [comment]
输出成什么配置

**Comment by harryyifei** [comment]
输出成 Surge 的配置，看了好像不需要特别标注，问题已经解决谢谢
