### ISSUE TITLE
[Feature] Support for tuic 5

### ISSUE THREAD

**Issue by Kare-Udon** [surgioproject/surgio#231]
[tuic 5](https://github.com/EAimTY/tuic/releases/tag/tuic-5.0.0) 发布，其配置与之前的版本不相兼容，是否计划支持 tuic 5 呢？
目前 Surge 已支持 tuic 5.

**Comment by geekdada** [comment]
马上会在 Surgio v3 中支持

**Comment by geekdada** [comment]
已发布
