### ISSUE TITLE
Surgio 3.0 在Vercel, Netlify等平台部署后运行都出错

### ISSUE THREAD

**Issue by ab00b** [surgioproject/surgio#240]
Surgio 3.0 在Vercel, Netlify等平台部署后运行都出错，甚至连Railway-demo仓库直接copy一份部署也会出同样的错误…
错误提提示全都一样， 正如 #239 中 所提到的那样，提示找不到/var/task/xxx/node_modules/surgio/build/index.js而不能运行

@geekdada

**Comment by ShadowsSide** [comment]
我这几天也遇到了，但是上个月28号修改过配置还可以重新生成配置的（版本如下）

Core: v3.0.1
Backend: v2.0.0

**Comment by geekdada** [comment]
了解，等我看一下

**Comment by geekdada** [comment]
新增了一个 Netlify 的 demo，麻烦修改一下你的 `netlify.toml`。另外 Vercel 不再提供支持。

https://github.com/surgioproject/netlify-demo
