### ISSUE TITLE
关于nodeList的name是否可以按照不同的机场添加自定义的不同的后缀名

### ISSUE THREAD

**Issue by stack-brain** [surgioproject/surgio#247]
关于nodeList的name是否可以按照不同的机场添加不同的后缀名

多个机场可以根据自己添加的name后缀名，可以快速区分这个节点是哪个机场来源？不知道目前是否支持呢

**Comment by PaiJi** [comment]
可以通过 _Provider_ 的 _renameNode_ 函数实现，参考文档：https://surgio.js.org/guide/custom-provider.html#provider-renamenode：
```
  renameNode: (name) => {
    return `机场名称-${name}`
  },
```

**Comment by stack-brain** [comment]
nice
