### ISSUE TITLE
surge 不支持默认为 Trojan 增加 alpn 选项

### ISSUE THREAD

**Issue by EstrellaXD** [surgioproject/surgio#248]
## 问题描述

v3 版本后 surgio 默认会为 Trojan 协议增加一个 alpn 的字段：
```
tls13=false, skip-cert-verify=true, alpn=h2,http/1.1
```

但是 surge 目前不支持这个字段，导致生成的配置文件内的所有 Trojan 协议都报错了。

在文档中搜索后未找到如何关闭这一字段的选项，请问是否可以为 surge 默认关闭。

**Comment by spencercjh** [comment]
+1

**Comment by geekdada** [comment]
会在下个版本修复
