### ISSUE TITLE
clash core 能力没有同步到 gateway 中

### ISSUE THREAD

**Issue by hunshcn** [surgioproject/surgio#257]
https://github.com/surgioproject/surgio/commit/654ceba8818a83e203eaddf5d9b56914462cb62f

这个功能 getEngine 的 options 在 gateway 没有读取并传递，导致 gateway 场景下 clashCore 配置无效

**Comment by geekdada** [comment]
Oops

**Comment by hunshcn** [comment]
当然如果能通过 user-agent 识别 core 类型可能会是最好的方法

**Comment by geekdada** [comment]
这个功能一开始没有想太透彻。Web 应用里的模板引擎通常只会实例化一次，这是基于性能考量的，这就意味着 filter 这样的静态处理方法无法接受请求上下文。
在之前的实现里也有另一个问题，就是模板引擎实例化引用的是 `surgioConfig.clashConfig`，无法接收到节点内部的 `nodeConfig.clashConfig`。这个问题很可能迷惑用户，所以我可能会在后面的大版本中去掉这个功能。

**Comment by geekdada** [comment]
我暂时先不关闭这个 issue，等我想一下如果没有好的办法再关吧。

**Comment by geekdada** [comment]
请升级 @surgio/gateway@2.1.1
暂时先这样吧
