### ISSUE TITLE
Vless Not supported in custom provider

### ISSUE THREAD

**Issue by damoncoo** [surgioproject/surgio#258]
<img width="1125" alt="313545337-4e9d2305-214b-4864-8356-5f106b73c1a7" src="https://github.com/surgioproject/surgio/assets/4880373/f029ebb0-de73-45d8-9a31-a19335078e62">
文档里面有vless的支持，但是运行报错，surigo是3.6.3

**Comment by geekdada** [comment]
https://github.com/surgioproject/surgio/releases/tag/v3.6.4
