### ISSUE TITLE
请求支持 clash-meta 的配置

### ISSUE THREAD

**Issue by fbigun** [surgioproject/surgio#259]
希望可以支持 getClashMetaNodes 函数 可以支持输出 vless 节点; ClashMete 现在已改名叫 [mihomo](https://github.com/MetaCubeX/mihomo)

文档中 ： [getclashnodes](https://surgio.js.org/guide/custom-template#getclashnodes)

```
提示

[Clash 规则维护指南](https://surgio.js.org/guide/client/clash)
支持输出 Shadowsocks, Shadowsocksr, HTTPS, Snell, Vmess, Trojan 节点
```

**Comment by geekdada** [comment]
1. 该方法已经支持 VLESS，请开启对应 `clashConfig.enableVless`
2. 暂时不修改 Clash 相关方法命名
