### ISSUE TITLE
某个机场无法作为Provier

### ISSUE THREAD

**Issue by kkfive** [surgioproject/surgio#267]
地址：https://gist.githubusercontent.com/kkfive/10c9eff9009476ef84374d43949db6aa/raw/node.yaml
节点来自机场私房菜，服务器地址和uuid已做随机处理，节点是substore处理过的，相同配置的其他节点没有出问题

**Comment by kkfive** [comment]
![image](https://github.com/surgioproject/surgio/assets/82026204/02a1fabc-3890-4c21-91f0-56caee8932a5)

**Comment by geekdada** [comment]
有个 bug，我修一下
