### ISSUE TITLE
provider可以获取API请求的customParams吗？

### ISSUE THREAD

**Issue by Maasea** [surgioproject/surgio#96]

**Comment by geekdada** [comment]
请写清楚使用场景和期望的效果

**Comment by Maasea** [comment]
> 请写清楚使用场景和期望的效果

使用场景:
通过请求参数来更改provider里写死的参数，比如url,udpRelay……

期望效果:

```  
请求传入参数
https://url?udpRelay=false&subUrl=xxxx

Surgio.conf.js 文件:

customParams:{
udpRelay:true,
subUrl:’’
}
 
Provider 文件:

export.module={
url:customeParams.subUrl,
udpRelay: customeParams.udpRelay
}
``` 
ps:可以设置远程节点的更新间隔吗？好像不是每次请求都会重新从订阅链接里获取节点。

**Comment by geekdada** [comment]
这个需求我会考虑。

你的另一个问题，见这里 https://surgio.royli.dev/guide/env.html#surgio-provider-cache-maxage

**Comment by yuhaowin** [comment]
请问现在支持通过 param 动态传入订阅 url，然后给 provider 使用嘛。

场景是现在机场的订阅链接经常性失效，希望通过 param 动态传入订阅链接。
